<?php

namespace Gaoren\VendorsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

      public function checkProductOwnership($product_id, $user_id)
      {
            $check = $this->getEntityManager()->getRepository( 'GaorenVendorsBundle:Product' )
                  ->createQueryBuilder( 'p' )
                  ->where( 'p.id = :id AND p.user = :user' )
                  ->setParameters( array(
                          'id' => $product_id,
                          'user' => $user_id
                  ) )
                  ->getQuery()
                  ->execute();
            
            return $check;
      }

}